### PR TITLE
Add testing setup

### LINKED ISSUE #104: Start creating unit tests?
There should be some way to unit test the JS stuff. I think one of the primary obstacles is having a way to import/export certain functions from files.

### PR DESCRIPTION
**Pull request by cktang88**
Sets up testing with [jest](https://jestjs.io/docs/en/getting-started). Use `npm test`.
~Currently started implementing a test for `GeneralStoreRenders.test.js` that doesn't work due to use of `random` which is undefined?~
Also the git history is a little messy :(

Closes #104

### CODE REVIEW

**Comment by monsagri** [comment]
Random is a global variable (think it is passed down from SugarCube - either that or Tweego)
There's an entry with all global variables in the eslintrc, you'll have to either import or mock their functionality or find a different way around it.

**Comment by cktang88** [comment]
Thanks @monsagri , fixed.

**Comment by monsagri** [comment]
Are there any real downsides to using a stronger library though? 
It's all just dev dependencies after all.

**Comment by cktang88** [comment]
Jest has pretty output, readable errors, parallel test execution, as well as a bunch of other useful standardized methods ([](https://jestjs.io/docs/en/expect)). If we plan to have many tests eventually, it'll be easier to scale than rolling our own script.

**Comment by Glinkis** [comment]
Probably, yeah. Just thought bringing up options.

**Comment by ryceg** [comment]
Hi @cktang88, after some discussion, we are thinking that we are going to change the license of the generator from GPL3 to MIT, in order to make it more accessible, and also stop the "infectious" license from spreading- this way, we will be able to integrate the generator into third party applications, and let people use the generator how they wish. 

However, in order to do this, we need to obtain permission from everyone who has contributed to the project- since you contributed under the GPL3 license, that doesn't mean that you would necessarily be okay with changing to the MIT license. 

You are under no obligation to provide license to use your code under the MIT license- if you do not agree with the license change then we can remove your code and make a fork of the generator without it, just let me know.

Thanks!

Rhys

**Comment by cktang88** [comment]
Hey @ryceg , I fully approve all my contributions to this project being licensed under MIT!

**Pull request merged**
