### PR TITLE
Bug-Fixes

### LINKED ISSUE #449: Images are missing alt text
The "Support Me...","Join Our Discord" and "Visit Our Github" link images need to have associated alt text. This can be the same as the text on the images. This will also fix a problem with the parent <a> tags not actually having link text, as the alt text in the image will fulfill this need.

### LINKED ISSUE #450: Tippy may not be accessible for desktop users using screen-readers
It looks like there may be some issues with the tool-tip implementation for desktop users that also use a screen-reader or voice assistant. It looks like this might only be binding to the "touchend" or "focus" event and not a "click" or "mouseup" event. This may make the tool-tips effectively invisible for some screen-readers when the browser is being used in a standard desktop mode. Screen-readers will typically look for an actual click-type event in order to read out the dialogue text from the tool-tip.

I am not 100% sure this is an issue as I don't have access to my work tools on this machine and I cannot actually access the generator on that network. Would recommend seeing if we can get actual users of assistive technologies to validate this as an issue.

### PR DESCRIPTION
**Pull request by ryceg**
## What does this do?

Adds accessibility labels to listboxes and tippys.

Still haven't included labels on textboxes, which is why this is a draft.

## How was this tested? Did you test the changes in the compiled `.html` file?

`.html`

## Is there a [GitHub Issue](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues?q=is%3Aopen+is%3Aissue) that this is resolving?

Closes #449
Closes #450

### CODE REVIEW

**Comment by Glinkis** [comment]
There is a large amount of repeated code with the tooltips. Perhaps we could Create a function which constructs these elements via a call instead? Something like `tooltip(title, text)`?

**Comment by ryceg** [comment]
I agree that it's a little frustrating for all of the tooltips to need `class="tip" role="tooltip" tabindex="0"`. I'm not sure how a function would work, since it needs the `</span>`. We could perhaps have it insert the stuff via jQuery element selection as part of the passage load or something? We'd only be saving a couple strings, but it would look nicer.

**Comment by Glinkis** [comment]
Wouldn't it work if the function just returns a string with the span included?

**Comment by ryceg** [comment]
My issue with that is that it leaves a supposedly orphaned `</span>`; ideally we would preserve the structure of the html so somebody looking at the code doesn't think that there's a bit missing.

**Comment by Glinkis** [comment]
Not sure I follow. Wouldn't it work to just replace 
```html
<span class="tip" role="tooltip" tabindex="0" title="title">text</span>
```
with this?
```js
function tooltip(title, text) {
  return `<span class="tip" role="tooltip" tabindex="0" title="${title}">${text}</span>`
}
````
```
<<print tooltip("title", "text") />>
```

**Comment by ryceg** [comment]
That would result in some very ugly strings being passed and then interpreted by SugarCube; 

```
<<print lib.createTippyFull("How wealthy is the patronage?", `<label for="numberslider-input-townbuildingscurrentpassageindexrollwealth">Smithy Wealth</label>: <<numberslider "$town.buildings[$currentPassage.index].roll.wealth" $town.buildings[$currentPassage.index].roll.wealth 1 100 1>>`)>>

```

Whereas at least the hierarchy (and syntax highlighting) is kept intact at the moment;

```
<span class="tip" role="tooltip" tabindex="0" title="How wealthy is the patronage?"><label for="numberslider-input-townbuildingscurrentpassageindexrollwealth">Smithy Wealth</label>: <<numberslider "$town.buildings[$currentPassage.index].roll.wealth" $town.buildings[$currentPassage.index].roll.wealth 1 100 1>></span>
```

**Comment by Glinkis** [comment]
Right, I see what you mean.  It's not really a practical difference, but rather a syntactical one.

**Comment by ryceg** [comment]
Right. All the same, it makes sugarcube code even _harder_ to read than it already is. Plus, initial tests of the code I posted don't seem to be promising for it working smoothly. It might be simpler to construct a function that adds the requisite tags and such to elements tagged with the `tip` class; it's not ideal that we'd need to either manually include it on every page where it is needed, or have it run on every passage. Seems any way we go, there's gonna be some uuuugly code.

**Comment by Glinkis** [comment]
Can we run it as an event when the passage changes? I think there should be an event we can hook into for that.

**Comment by ryceg** [comment]
There is- might need to check to see if anything nested inside a `<<linkreplace>>` would also fire the :passagestart event.

**Comment by Glinkis** [comment]
Hmm, and event which fores whenever any content is changed would be nice.

**Comment by ryceg** [comment]
It doesn't look like there is one- most of the offending manually added tooltips are top-level, and would be caught by the `:passageend` event, but it'd still be nice to not have to remember.

**Pull request merged**
