### PR TITLE
Add additional town prefixes and suffixes

### PR DESCRIPTION
**Pull request by Fleker**
Some additional names I've used in the past

### CODE REVIEW

**Review by Glinkis — APPROVED** [review]
Looks good to me!

**Review by ryceg — APPROVED** [review]

**Comment by ryceg** [comment]
Hi @Fleker, after some discussion, we are thinking that we are going to change the license of the generator from GPL3 to MIT, in order to make it more accessible, and also stop the "infectious" license from spreading- this way, we will be able to integrate the generator into third party applications, and let people use the generator how they wish. 

However, in order to do this, we need to obtain permission from everyone who has contributed to the project, since you contributed under the GPL3 license, that doesn't mean that you would necessarily be okay with changing to the MIT license. 

You are under no obligation to provide license to use your code under the MIT license- if you do not agree with the license change then we can remove your code and make a fork of the generator without it, just let me know.

Thanks!

Rhys

**Comment by Fleker** [comment]
Yes @ryceg you have my permission.

**Comment by ryceg** [comment]
Thanks a lot! Happy Hacktoberfest.

**Pull request merged**
