### PR TITLE
added race editing without changing pages

### PR DESCRIPTION
**Pull request by ryceg**

### CODE REVIEW

**Review by Glinkis — APPROVED** [review]
Looks good to me. Though I'm not very familiar with how the `<<liveblock>>` macro works.

**Comment by ryceg** [comment]
It essentially replaces the janky combo of `<<linkreplace>><<replace "#selector">>` stuff. Will be converting over things to it. Fingers crossed that your approval counts for hacktoberfest!

**Comment by Glinkis** [comment]
It does not, but I already filled my quota for this year.

**Comment by ryceg** [comment]
Yep, my own count. It does!

**Pull request merged**
