### PR TITLE
Convert-to-TypeScript

### PR DESCRIPTION
**Pull request by ryceg**
## What does this do?

Converts following:
- createTavern
- createBartender
- tavernSleep (is now renamed to getWakeUpByWealth

## How was this tested? Did you test the changes in the compiled `.html` file?

Currently broken, and `getWakeUpByWealth` doesn't appear to be registering as a function in `main.ts`.

### CODE REVIEW

**Comment by Glinkis** [comment]
This is getting a bit unwieldy, and since so many files are touched by this I'm not sure which ones I can safely work in new branches. We should look at fixing the errors and merging.

**Comment by ryceg** [comment]
Agreed, sorry. Things got carried away! Still can't figure out why my `yarn type` isn't working.

**Comment by Glinkis** [comment]
Things in `lib` does currently not really need to be imported as modules, unless it's a type or interface, in which case it would use `ìmport type`.

**Comment by ryceg** [comment]
Are we preferring to access it via `lib` rather than import? I assumed that it'd be easier to keep all Typescript files using imports.

**Comment by Glinkis** [comment]
It's kind of used in the same way, and provides the same intellisense (I think). We'll probably want to migrate to using the imports at some point, so we can treeshake properly. But I would put that in separate PR's to make overview and debugging easier.

**Review by Glinkis — APPROVED** [review]
`ts-ignore` is better for fixable errors. `expect-error` is mainly used for tests that check for errors that are also caught by type checks.

**Pull request merged**
