### PR TITLE
Refactor location vegetation and plants to an array of integers

### LINKED ISSUE #221: Refactor location vegetation to an integer, rather than an array.
Currently, vegetation and plants are array based; 

`setup.townData.terrain[town.terrain].location[town.location].vegetation` is: `['sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick']`, and `setup.townData.terrain[town.terrain].location[town.location].plants` is: `['shrubs', 'bush', 'windswept trees', 'windswept trees', 'windswept trees']`. 

This is obviously a huge waste of LoC, and can be refactored quite easily, and include more detail.

### PR DESCRIPTION
**Pull request by zakivanovic**
Fixes #221

### CODE REVIEW

**Comment by zakivanovic** [comment]
Ok, sounds good. I'll change the code adding a weigthRandom function

**Comment by zakivanovic** [comment]
@Glinkis Is this better?

**Comment by Glinkis** [comment]
Yeah, I like this a lot better.

**Comment by WishingOnAWendy** [comment]
Nice work

**Pull request merged**
