### PR TITLE
Adds webpack plugin that copies over images for local development

### PR DESCRIPTION
**Pull request by kevoneil**
## What does this do?
- Adds `CopyWebpackPlugin`
- Modifies image paths in tweego file

## How was this tested? Did you test the changes in the compiled `.html` file?
Tested locally. 

## Is there a [GitHub Issue](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues?q=is%3Aopen+is%3Aissue) that this is resolving?
https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/400

## We are shifting from a GPL3 license to MIT. Are you okay with us relicensing your code contributions under this new license?
Yes

All images are resolving locally now.
Screen Shot 2020-11-28 at 1 16 29

### CODE REVIEW

**Comment by Glinkis** [comment]
There is no `cp` command in windows. And this won't work with the `start` command either. It's better to add this in the webpack configuration, or in the build script file itself.

**Comment by Glinkis** [comment]
Its also best not to just smack everything directly in the gh-pages folder, but have things sorted into subfolders, or even better to keep the previous folder hierarchy.

**Comment by kevoneil** [comment]
> Its also best not to just smack everything directly in the gh-pages folder, but have things sorted into subfolders, or even better to keep the previous folder hierarchy.

Agreed, everything should be moved into the `src/Resources` path with the new command

**Comment by kevoneil** [comment]
> There is no cp command in windows. And this won't work with the start command either. It's better to add this in the webpack configuration, or in the build script file itself.

Sorry, missed this comment. Yeah, looks like it's best to use a webpack plugin after all

**Comment by Glinkis** [comment]
This looks pretty good. I'll have to test it before approving.

Also, ai'm a bit concerned that this will also copy the CSS files, which are already bundled in the html. Perhaps we could.add an exclusion for those.

**Comment by kevoneil** [comment]
@Glinkis I xdd. I'm not seeing any `.css` files in the `src/Resoures` file. Do you think some stylesheet files will be moved there in the near future? Looks like all styles are included in the `head` element.

If so, we could use the `ignore` option here:
https://webpack.js.org/plugins/copy-webpack-plugin/

```
Eigengrau-s-Essential-Establishment-Generator/gh-pages/src  kevoneil/adds-command-to-copy-images-fonts ✔                                                7h23m
▶ ls Resources
0001.png             discord.svg          patreon.svg
0002.png             footer.png           sidebarbanner.svg
Fonts                github.svg           sidebars.png
backgroundpaper.webp kofi.svg             table-wrap.png
banner.svg           note-wrap.png        townIllustration.jpg
bottom 0001.png      paper2.jpg
```

**Pull request merged**
