### PR TITLE
Migrate to typescript

### PR DESCRIPTION
**Pull request by Glinkis**
## What does this do?

Fixes a few issues with the recent rollup update, and migrates another file to typescript.

## How was this tested? Did you test the changes in the compiled `.html` file?

Tested though inspection of the output init.js file, as well as type checking.

## Is there a [GitHub Issue](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues?q=is%3Aopen+is%3Aissue) that this is resolving?

No.

### CODE REVIEW

**Comment by Glinkis** [comment]
@noahlange Any thought on this?

**Comment by noahlange** [comment]
> @noahlange Any thought on this?

Looks good. I was reading through the `Setup` declarations when I realized structuring things a little differently might allow us to avoid some boilerplate. Exporting each file's functions (instead of merging them into the global scope within the file) and importing them into an `index.ts` that performs handles all the assignment and `Setup` interface declarations would make things quite a bit cleaner.

```typescript
// ./foo/bar.ts
export function getFooBar() {}
export function getFooBarBaz() {}
```

```typescript
// ./foo/index.ts
import { getFooBar, getFooBarBaz } from './bar'

declare global {
  interface Setup {
    getFooBar: typeof getFooBar
    getFooBarBaz: typeof getFooBarBaz
  }  
}

setup.getFooBar = getFooBar
setup.getFooBarBaz = getFooBarBaz

export { getFooBar }
```

```typescript
// main.ts
import './foo';
```

**Comment by Glinkis** [comment]
Yeah, I definitely agree. Reason I didn't was that every function would need to touch two files, but I suppose we do that with the current solution as well. I'll update the PR with your suggestion before we merge this.

Thanks for the input.

**Comment by Glinkis** [comment]
@ryceg I've added a few `FIXME` comments that it would be awesome if you could look at. I'll probably still merge this, but those needs to be fixed at some point.

**Pull request merged**
