### PR TITLE
Refactor age.js

### PR DESCRIPTION
**Pull request by cktang88**
Much shorter :)

### CODE REVIEW

**Comment by cktang88** [comment]
Manually tested 
image

**Comment by ryceg** [comment]
just caught the uninitialised variable ranks. Pushed an update, no worries!

**Comment by cktang88** [comment]
ah, sorry! also using `const` is probably better than `var`

**Comment by ryceg** [comment]
You're very right, It's a bad habit. Thanks!

**Comment by cktang88** [comment]
I just noticed, this isn't going to work if `age <= 0`

**Pull request merged**
